spring:
  datasource-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  datasource:
    username: h2
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    password: pass
welcome:
  message: "Welcome to Employee CRUD"
server:
  port: 8084
